### ISSUE TITLE
Javascriptcore fast native calls

### ISSUE THREAD

**Issue by supercranky** [openaphid/AJ#2]
I have done some research about optimizing our HTML5 game wrapper based on Ejecta. And one finding is that calls to injected native functions are much slower than regular javascript functions. I noticed you came to the same conclusion and that you somehow modified Javascriptcore to bypass this. Is there an easy shortcut to make fast native calls? I'm trying to figure it out by reading the source to AJ, maybe you could point me in the right direction?

**Comment by openaphid** [comment]
I have not been working on JavaScriptCore for a long time, below are my wild guesses:
1. If your native functions are injected by the JavaScriptCore C Binding APIs, then the performance is limited as there is a pthread lock inside the binding APIs
2. Injecting functions into the underlying JSC C++ object was the fastest way when I was building OpenAphid-Engine, please refer to the function table of [AJNode](https://github.com/openaphid/Runtime/blob/master/DISCONTINUED/OpenAphid/Derived-iOS/AJNode_table.in.h#L50) for example.
3. Please don't use Objective-C type coding to expose and wrap the return value and parameters of your native functions, which is easy to implement but doesn't perform well.

**Comment by supercranky** [comment]
Great info! Yes, Ejecta is using the C Binding API and I suspected there was a thread lock stalling things in there. Maybe you could alter the API to have a non-locking version? I will check out how you did it.

I'm also trying to compile a JIT-enabled version of JavaScriptCore as a static library for Android (using OSX), but it seems like a really complex task. I'm guessing you don't have a project with working build-files lying around? :)

**Comment by openaphid** [comment]
No, I chose to work directly on the underlying C++ object and went away from the C binding API.

The lock inside the C binding API is necessary as it guarantees thread safety due to JSC's single thread nature.

There is another limitation of C API: it's not possible to make native objects work seamlessly with the garbage collector, which may shift memory management to business logic as what we can see in [Titanium](https://wiki.appcelerator.org/display/guides2/Managing+Memory+and+Finding+Leaks).

It took me like a week to enable JIT for Android. It's a port from the version of JSC shipped in [iOS 4.3.3](https://opensource.apple.com/source/JavaScriptCore/JavaScriptCore-721.26/), which only employs the baseline JIT.

I can still recall some tough tasks:
1. Recreate NDK build file
2. Fix compile and link issues for ICU, pthread and stdc++, etc
3. Build a small JNI wrapper framework based on [WTF](https://trac.webkit.org/wiki/SourceDirectory)

But I have no idea how to enable JIT for a newer version of JSC as the JIT architecture has involved [drastically](http://trac.webkit.org/wiki/JavaScriptCore)

**Comment by supercranky** [comment]
Not sure I will manage to recreate your efforts but I'll try! 

Thanks for taking the time to answer this!
